In [1]:
import pandas as pd
from prepare import *

In [2]:
df = pd.read_csv('new_extracted_data_jared_time_1.csv')
df1 = pd.read_csv('new_extracted_data_jared_time_2.csv')
df2 = pd.read_csv('new_extracted_data_jared_time_3.csv')
df3 = pd.read_csv('new_extracted_data_jared_time_4.csv')
df4 = pd.read_csv('new_extracted_data_jared_time_5.csv')
df5 = pd.read_csv('new_extracted_data_jared_time_6.csv')
df6 = pd.read_csv('new_extracted_data_jared_time_7.csv')
df7 = pd.read_csv('new_extracted_data_jared_time_8.csv')
df8 = pd.read_csv('new_extracted_data_jared_time_9.csv')
df9 = pd.read_csv('new_extracted_data_jared_time_10.csv')
df10 = pd.read_csv('new_extracted_data_jared_time_11.csv')
df11 = pd.read_csv('new_extracted_data_jared_time_12.csv')
df12 = pd.read_csv('new_extracted_data_jared_time_13.csv')
df13 = pd.read_csv('new_extracted_data_jared_time_14.csv')
df14 = pd.read_csv('new_extracted_data_jared_time_15.csv')
df15 = pd.read_csv('new_extracted_data_jared_time_16.csv')
df16 = pd.read_csv('new_extracted_data_jared_time_17.csv')
df17 = pd.read_csv('new_extracted_data_jared_time_18.csv')
df18 = pd.read_csv('new_extracted_data_jared_time_19.csv')
df19 = pd.read_csv('new_extracted_data_jared_time_20.csv')
df20 = pd.read_csv('new_extracted_data_jared_time_21.csv')
df21 = pd.read_csv('new_extracted_data_jared_time_22.csv')
df22 = pd.read_csv('new_extracted_data_jared_time_23.csv')

In [3]:
df = pd.concat([df1, df2], axis=0, ignore_index=True)

In [4]:
df = pd.concat([df, df3], axis=0, ignore_index=True)

In [5]:
df = pd.concat([df, df4], axis=0, ignore_index=True)

In [6]:
df = pd.concat([df, df5], axis=0, ignore_index=True)

In [7]:
df = pd.concat([df, df6], axis=0, ignore_index=True)

In [8]:
df = pd.concat([df, df7], axis=0, ignore_index=True)

In [9]:
df = pd.concat([df, df8], axis=0, ignore_index=True)

In [10]:
df = pd.concat([df, df9], axis=0, ignore_index=True)

In [11]:
df = pd.concat([df, df10], axis=0, ignore_index=True)

In [12]:
df = pd.concat([df, df11], axis=0, ignore_index=True)

In [13]:
df = pd.concat([df, df12], axis=0, ignore_index=True)

In [14]:
df = pd.concat([df, df13], axis=0, ignore_index=True)

In [15]:
df = pd.concat([df, df14], axis=0, ignore_index=True)

In [16]:
df = pd.concat([df, df15], axis=0, ignore_index=True)

In [17]:
df = pd.concat([df, df16], axis=0, ignore_index=True)

In [18]:
df = pd.concat([df, df17], axis=0, ignore_index=True)

In [19]:
df = pd.concat([df, df18], axis=0, ignore_index=True)

In [20]:
df = pd.concat([df, df19], axis=0, ignore_index=True)

In [21]:
df = pd.concat([df, df20], axis=0, ignore_index=True)

In [22]:
df = pd.concat([df, df21], axis=0, ignore_index=True)

In [23]:
df = pd.concat([df, df22], axis=0, ignore_index=True)

In [24]:
df.drop_duplicates()

,airdragon_team100,assistsplayer_1,assistsplayer_10,assistsplayer_2,assistsplayer_3,assistsplayer_4,assistsplayer_5,assistsplayer_6,assistsplayer_7,assistsplayer_8,...,xp_7,xp_8,xp_9,chemtechdragon_team200,hextechdragon_team100,airdragon_team200,waterdragon_team200,riftherald_team200,inhibs_lost_team100,baron_team200
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,417.0,150.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,240.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,515.0,211.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,417.0,181.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,181.0,515.0,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9301,1.0,2.0,11.0,6.0,3.0,4.0,8.0,8.0,4.0,4.0,...,10870.0,8183.0,9527.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
9302,1.0,6.0,12.0,5.0,8.0,7.0,0.0,9.0,5.0,8.0,...,12615.0,9636.0,11073.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9303,1.0,13.0,6.0,5.0,6.0,5.0,6.0,2.0,5.0,11.0,...,10387.0,8209.0,9219.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN
9304,0.0,1.0,18.0,3.0,2.0,1.0,9.0,10.0,19.0,3.0,...,11508.0,10279.0,9972.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN
9305,0.0,4.0,14.0,8.0,2.0,2.0,12.0,5.0,13.0,2.0,...,9599.0,11534.0,11109.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN

In [25]:
df = clean(df)

In [29]:
df

,BlueTeamAirDragon,BlueTopAssists,RedSupportAssists,BlueJungleAssists,BlueMidAssists,BlueADCAssists,BlueSupportAssists,RedTopAssists,RedJungleAssists,RedMidAssists,...,BlueSupportKda,RedTopKda,RedJungleKda,RedMidKda,RedBotKda,RedSupportKda,BlueTeamKdaDifference,BlueJungleGankHeavy,RedJungleGankHeavy,BlueTeamJungleDiffy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,-4.0,-5.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,-7.0,0.0,-7.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.75,0.00,0.0,0.00,-1.00,0.00,3.00,-4.0,-8.0,4.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,-5.0,5.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,-5.0,0.0,-5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9301,1.0,2.0,11.0,6.0,3.0,4.0,8.0,8.0,4.0,4.0,...,6.00,7.50,17.0,-3.75,3.75,6.75,-3.00,884.0,1516.0,-632.0
9302,1.0,6.0,12.0,5.0,8.0,7.0,0.0,9.0,5.0,8.0,...,-4.25,7.25,7.5,5.50,1.75,9.25,0.00,497.0,695.0,-198.0
9303,1.0,13.0,6.0,5.0,6.0,5.0,6.0,2.0,5.0,11.0,...,5.25,4.75,8.5,9.25,3.25,3.50,0.75,492.0,581.0,-89.0
9304,0.0,1.0,18.0,3.0,2.0,1.0,9.0,10.0,19.0,3.0,...,0.75,17.00,13.5,22.00,6.50,13.00,-77.25,416.0,-13.0,429.0
9305,0.0,4.0,14.0,8.0,2.0,2.0,12.0,5.0,13.0,2.0,...,5.75,-1.25,12.5,8.75,16.75,5.00,-12.75,904.0,592.0,312.0

In [27]:
#df.fillna(0,inplace = True)

In [30]:
df.to_csv('timestamped_df_updated.csv')