In [11]:
import pandas as pd
from prepare import *

In [4]:
df1 = pd.read_csv('new_extracted_data_jared_time_5.csv')
df2 = pd.read_csv('new_extracted_data_jared_time_10.csv')
df3 = pd.read_csv('new_extracted_data_jared_time_15.csv')
df4 = pd.read_csv('new_extracted_data_jared_time_20.csv')

In [5]:
df = pd.concat([df1, df2], axis=0, ignore_index=True)

In [6]:
df = pd.concat([df, df3], axis=0, ignore_index=True)

In [7]:
df = pd.concat([df, df4], axis=0, ignore_index=True)

In [9]:
df.drop_duplicates()

,airdragon_team100,assistsplayer_1,assistsplayer_10,assistsplayer_2,assistsplayer_3,assistsplayer_4,assistsplayer_5,assistsplayer_6,assistsplayer_7,assistsplayer_8,...,xp_6,xp_7,xp_8,xp_9,waterdragon_team200,hextechdragon_team100,riftherald_team200,airdragon_team200,chemtechdragon_team200,inhibs_lost_team100
0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,2.0,0.0,...,2080.0,1691.0,1886.0,1351.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,2007.0,1655.0,2079.0,1375.0,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,1.0,2.0,...,1688.0,1575.0,1819.0,303.0,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1540.0,1512.0,1747.0,961.0,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,1.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,0.0,...,1539.0,1809.0,1567.0,1285.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1.0,2.0,8.0,6.0,3.0,4.0,6.0,6.0,4.0,3.0,...,10631.0,9458.0,6582.0,8136.0,NaN,NaN,1.0,NaN,1.0,NaN
1688,1.0,6.0,9.0,4.0,6.0,7.0,0.0,6.0,3.0,5.0,...,8517.0,9953.0,7718.0,9506.0,NaN,NaN,NaN,NaN,NaN,NaN
1689,1.0,10.0,6.0,1.0,5.0,3.0,4.0,2.0,5.0,10.0,...,10382.0,9591.0,7506.0,8810.0,NaN,NaN,1.0,NaN,NaN,NaN
1690,0.0,1.0,16.0,3.0,1.0,1.0,7.0,7.0,14.0,3.0,...,11580.0,9195.0,7279.0,7973.0,NaN,1.0,1.0,1.0,NaN,NaN
1691,0.0,4.0,13.0,7.0,2.0,2.0,11.0,4.0,12.0,2.0,...,10181.0,8594.0,8903.0,8958.0,NaN,NaN,1.0,NaN,NaN,NaN

In [12]:
df = clean(df)

In [13]:
df

,airdragon_team100,assistsplayer_1,assistsplayer_10,assistsplayer_2,assistsplayer_3,assistsplayer_4,assistsplayer_5,assistsplayer_6,assistsplayer_7,assistsplayer_8,...,BlueTeamWards,RedTeamWards,BlueTeamAssists,RedTeamAssists,BlueTeamXp,RedTeamXp,BlueTeamTotalGoldDifference,RedTeamTotalGoldDifference,BlueTeamMVPKills,RedTeamMVPKills
0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,2.0,0.0,...,5,6,3,5,7106,8125,-1334,1334,1.0,2.0
1,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,6,5,0,4,7085,8491,-1923,1923,2.0,2.0
2,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,1.0,2.0,...,43,7,4,5,6584,5928,315,-315,3.0,2.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,7,4,2,3,7304,7111,-932,932,1.0,2.0
4,0.0,1.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,0.0,...,5,9,6,2,6466,6549,1313,-1313,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1.0,2.0,8.0,6.0,3.0,4.0,6.0,6.0,4.0,3.0,...,23,44,21,29,42187,42363,1461,-1461,9.0,14.0
1688,1.0,6.0,9.0,4.0,6.0,7.0,0.0,6.0,3.0,5.0,...,254,23,23,27,45126,44540,2037,-2037,9.0,6.0
1689,1.0,10.0,6.0,1.0,5.0,3.0,4.0,2.0,5.0,10.0,...,31,31,23,27,42447,43937,-5163,5163,6.0,6.0
1690,0.0,1.0,16.0,3.0,1.0,1.0,7.0,7.0,14.0,3.0,...,67,74,13,45,35965,42095,-12222,12222,6.0,11.0
1691,0.0,4.0,13.0,7.0,2.0,2.0,11.0,4.0,12.0,2.0,...,42,63,26,41,44347,42595,-497,497,10.0,8.0

In [14]:
df.fillna(0,inplace = True)

In [15]:
df.to_csv('timestamped_df.csv')